# Generated by Django 4.0.1 on 2022-07-18 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0002_alter_emailmodel_footer_alter_emailmodel_header'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailmodel',
            old_name='email',
            new_name='email_to',
        ),
    ]
