# Generated by Django 4.0.1 on 2022-07-19 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskQueues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 19, 19, 51, 9, 937549)),
        ),
    ]
